[package]
name = "rust_chip8"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "lib"
path = "lib/lib.rs"

[dependencies]
sdl2 = "0.38.0"
rand = "0.9.2"
